### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by Felda01** [TIS2018-FMFI/headis#13]
Create database model

**Comment by rychtovy24** [comment]
![database](https://user-images.githubusercontent.com/36670170/48771667-4b8ad380-ecc2-11e8-993a-8c68531e0025.png)

**Comment by hbalazs09** [comment]
Prosím opraviť tabuľku matches - treba vymazať položky user_id_1, user_id_2, sú irelevantné, lebo tabuľka challanges, ktorá je pripojená s tabuľkou matches už obsahuje tie hodnoty.

**Comment by rychtovy24** [comment]
![database](https://user-images.githubusercontent.com/36670170/48774677-32d2eb80-eccb-11e8-8761-c87b53a7ad92.png)

**Comment by hbalazs09** [comment]
Ok, databázový model je v poriadku.

**Comment by rychtovy24** [comment]
Posledne zmeny
![database](https://user-images.githubusercontent.com/36670170/49082842-2579ac00-f24b-11e8-9bca-f00f1a6b58d9.png)

**Comment by hbalazs09** [comment]
Prosim upraviť:
 - vymazať položky user_id_1, user_id_2, sú irelevantné, lebo tabuľka challanges, ktorá je spojená s tabuľkou matches už obsahuje tie hodnoty
 - pridať tabuľku "comments"

**Comment by rychtovy24** [comment]
![database](https://user-images.githubusercontent.com/36670170/49116045-b0cf5d80-f29c-11e8-9019-1fc8b5fe0ad3.png)

**Comment by hbalazs09** [comment]
Model je v poriadku.

**Comment by rychtovy24** [comment]
[https://github.com/TIS2018-FMFI/headis/blob/navrh/database.png](url)

**Comment by hbalazs09** [comment]
Databázový model je v poriadku.
