### ISSUE TITLE
GUI - rebríčková pyramída a štatistiky

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#17]

**Comment by marian1107** [comment]
Rebríčková pyramída a štatistiky - PC

![rebrickova](https://user-images.githubusercontent.com/24941336/48998212-14e60a80-f153-11e8-98cc-b8d9584e9910.jpg)

Rebríčková pyramída a štatistiky - Mobil

![rebrickova_mobil](https://user-images.githubusercontent.com/24941336/48998222-216a6300-f153-11e8-89fc-9541fafc59cc.jpg)

**Comment by rychtovy24** [comment]
Rebríčkovú pyramídu na mobilnej appke by sme skôr mohli reprezentovať ako zoznam prvkov pod sebou a medzi levelmi bude väčšia medzera.

**Comment by marian1107** [comment]
Opravená mobilná verzia stránky:


![mobil](https://user-images.githubusercontent.com/24941336/49103449-b0729a80-f27b-11e8-8b76-8e2b090ed30d.jpg)

**Comment by rychtovy24** [comment]
vsetko v poriadku
