### ISSUE TITLE
GUI - výzva a zápas

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#18]

**Comment by Felda01** [comment]
Vyzva - vyzvany
![vyzva-zapas-vyzvany](https://user-images.githubusercontent.com/15653567/48977316-56fe4600-f098-11e8-8237-66b236175bed.png)

Vyzva - vyzyvatel
![vyzva-zapas-vyzyvatel](https://user-images.githubusercontent.com/15653567/48977317-56fe4600-f098-11e8-9766-5fb36b137a3d.png)

**Comment by marian1107** [comment]
Je to ok. Som s tým spokojný.

**Comment by marian1107** [comment]
Treba ešte dorobiť mobilnú verziu.

**Comment by Felda01** [comment]
![image](https://user-images.githubusercontent.com/15653567/49073194-2a7e3180-f232-11e8-987e-f072d2c2dd46.png)

**Comment by marian1107** [comment]
Všetko je v poriadku.

**Comment by marian1107** [comment]
Doplniť zápas.

**Comment by Felda01** [comment]
![vyzvany](https://user-images.githubusercontent.com/15653567/49332916-2cd7e700-f5b6-11e8-9882-054eaf57ac6a.png)
![vyzyvatel](https://user-images.githubusercontent.com/15653567/49332918-306b6e00-f5b6-11e8-85a7-d2cde87c0b25.png)

**Comment by rychtovy24** [comment]
vsetko spravne.
