### ISSUE TITLE
GUI - hlavná stránka

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#20]

**Comment by rychtovy24** [comment]
Prihlásený používateľ
![hlavna-prihlaseny](https://user-images.githubusercontent.com/36670170/48967886-928d0780-efe7-11e8-84ad-977f65416f2a.png)

**Comment by rychtovy24** [comment]
Mobilná verzia
![hlavna-mobilna](https://user-images.githubusercontent.com/36670170/48971340-70f84400-f018-11e8-9e74-f2c62daca3c6.png)

**Comment by hbalazs09** [comment]
GUI pre hlavnú stránku vyzerá dobre, je to takto v poriadku. Nemám čo dodať.
