### ISSUE TITLE
GUI - template

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#21]

**Comment by rychtovy24** [comment]
![template](https://user-images.githubusercontent.com/36670170/48971938-0dbedf80-f021-11e8-8bf6-646feede6169.png)

**Comment by rychtovy24** [comment]
Mobilná verzia
![mobil-template](https://user-images.githubusercontent.com/36670170/48971967-963d8000-f021-11e8-99e6-5dcf40119636.jpg)

**Comment by Felda01** [comment]
templaty su v poriadku, podla nich budeme robit ostatne.
