### ISSUE TITLE
server

### ISSUE THREAD

**Issue by Felda01** [TIS2018-FMFI/headis#24]
je kempelen.dai.fmph.uniba.sk

**Comment by pavelpetrovic** [comment]
pridal som subor db.txt do domovskeho adresara na servri s udajmi o db
a linku headis/ ktora smeruje na miesto, kde je ulozisko
pre https://kempelen.dai.fmph.uniba.sk/headis/
vratane logov servra (kde mozete hladat pripadne chyby v skriptoch)

subory, ktore maju byt pristupne na citanie (napr. skripty) by mali byt:

owner: headis
group owner: webheadis

prava: owner: rw,  group: r,  others: - 

tie adresare, kde budu skripty aj zapisovat (napr. pre upload obrazkov, cache a pod.) rovnako, ale este aj group: rw.

pouzite prikazy chmod, chown a chgrp na nastavenie tychto prav.

**Comment by Felda01** [comment]
nahrate na serveri a server pripraveny
