### ISSUE TITLE
Vytvorenie návrhu

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#25]

**Comment by Felda01** [comment]
- [ ] [Pouzite techologie](https://github.com/TIS2018-FMFI/headis/issues/26)

- [ ] [State diagram](https://github.com/TIS2018-FMFI/headis/issues/8)

- [ ] [Databazovy model](https://github.com/TIS2018-FMFI/headis/issues/13)

- [ ] [Component diagram](https://github.com/TIS2018-FMFI/headis/issues/10)

- [ ] [Spojene pouzivatelskeho rozhrania](https://github.com/TIS2018-FMFI/headis/issues/27)

- [ ] [Class diagram](https://github.com/TIS2018-FMFI/headis/issues/7)

- [ ][GUI - prihlasenie/registracia](https://github.com/TIS2018-FMFI/headis/issues/28)
