### ISSUE TITLE
Spojenie používateľského rozhrania

### ISSUE THREAD

**Issue by marian1107** [TIS2018-FMFI/headis#27]
Spojiť používateľské rozhranie do jedného obrázku.

**Comment by hbalazs09** [comment]
![gui_ver2](https://user-images.githubusercontent.com/6898537/49460005-a22efc00-f7f0-11e8-9705-19fa37ce160d.png)

**Comment by rychtovy24** [comment]
vsetko spravne poprepajane.

**Comment by marian1107** [comment]
Používateľské rozhranie je v poriadku.
