### ISSUE TITLE
GUI - prihlásenie, registrácia

### ISSUE THREAD

**Issue by marian1107** [TIS2018-FMFI/headis#28]
Treba vytvoriť GUI pre registráciu a prihlásenie.

**Comment by hbalazs09** [comment]
![prihlasenie](https://user-images.githubusercontent.com/6898537/49331440-3c970180-f59d-11e8-9a91-088ab027d1f3.png)
![prihlasenie_mobil](https://user-images.githubusercontent.com/6898537/49331441-3c970180-f59d-11e8-9219-3a30ea9f579e.png)
![registracia](https://user-images.githubusercontent.com/6898537/49331442-3c970180-f59d-11e8-9896-9e87110dd736.png)
![registracia_mobil](https://user-images.githubusercontent.com/6898537/49331443-3c970180-f59d-11e8-8c67-dbd1a52bc1f5.png)

**Comment by marian1107** [comment]
Dobre, som s tým spokojný.
