### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by Felda01** [TIS2018-FMFI/headis#4]
zapracovať zmeny

**Comment by pavelpetrovic** [comment]
poprosim este drobne upravy:
 - cislo 5 mozete rozdelit/upravit
 - chyba mi informacia o formate vysledku zapasov
 - uvazujete nad vysledkami rozdelenymi nad odohratymi a neodohratymi
 - cislo 16 rozvit
 - mozete pridat, ze informacie o hracovi sa zobrazia klikanim na pyramide
hned ako tieto drobnosti upravite, poslite, prosim, zadavatelovi a upozornite ho, aby si dokument
este dokladne pozrel, lebo podla neho system vyviniete. zaroven ho mozete poziadat o stretnutie k navrhu pouzivatelskeho rozhrania

**Comment by hbalazs09** [comment]
[katalog.pdf](https://github.com/TIS2018-FMFI/headis/files/2608087/katalog.pdf)
Upravil som katalog. Poprosim feedback.

**Comment by hbalazs09** [comment]
Katalog bol upraveny
[katalog.pdf](https://github.com/TIS2018-FMFI/headis/files/2620460/katalog.pdf)

**Comment by rychtovy24** [comment]
Katalog poziadaviek bol schvaleny zadavatelom. Suhlas je nahraty.
