### ISSUE TITLE
Vytvorenie Controller-ov

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#48]

**Comment by rychtovy24** [comment]
- [ ] [HomeController](https://github.com/TIS2018-FMFI/headis/issues/38)

- [ ] [AuthController](https://github.com/TIS2018-FMFI/headis/issues/39)

- [ ] [PyramidController](https://github.com/TIS2018-FMFI/headis/issues/40)

- [ ] [ManagerController](https://github.com/TIS2018-FMFI/headis/issues/41)

- [ ] [MatchController](https://github.com/TIS2018-FMFI/headis/issues/43)

- [ ] [SetController](https://github.com/TIS2018-FMFI/headis/issues/42)

- [ ] [ChallengeController](https://github.com/TIS2018-FMFI/headis/issues/45)

- [ ] [DateController](https://github.com/TIS2018-FMFI/headis/issues/46)

- [ ] [CommentController](https://github.com/TIS2018-FMFI/headis/issues/44)

- [ ] [UserController](https://github.com/TIS2018-FMFI/headis/issues/47)

**Comment by Felda01** [comment]
vsetky su vytvorene a pripravene
