### ISSUE TITLE
Informáciu o počte výziev

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#64]

**Comment by rychtovy24** [comment]
Pripravene na kontrolu

**Comment by Felda01** [comment]
mozno by sa tam hodilo dat preklad ked uz nebude moct vyzvat ziadnych hracov a tym padom tam dat if ze ak pocet je nula tak zaporna veta, inak pocet ktory ostava.

**Comment by Felda01** [comment]
preklad opraveny

**Comment by Felda01** [comment]
informacia sa zobrazuje spravne
