### ISSUE TITLE
Zálohovať históriu

### ISSUE THREAD

**Issue by rychtovy24** [TIS2018-FMFI/headis#65]

**Comment by Felda01** [comment]
pridat tam nieco select alebo tak, na zobrazenie starsich rocnikov 

- cez get parameter id season
- season model pridat function ktora vrati rok zaciatku a konca (t.j. 2018/2019)

**Comment by Felda01** [comment]
pripravene, dropdown v navigacii pri user a pyramid

**Comment by rychtovy24** [comment]
done
