### ISSUE TITLE
Moznost oznacit zapas ako neodohraty

### ISSUE THREAD

**Issue by Felda01** [TIS2018-FMFI/headis#72]

**Comment by Felda01** [comment]
stala sa taka vec ze chalani nemohli odohrat svoju vyzvu lebo jeden nahle ochorel a opat nahodilo 2:2. Preto mozno by bolo dobre doplnit tlacitko " zapas sa neodohral" a ponechat pocet vyziev.

**Comment by Felda01** [comment]
pridat bool policko, upravit pocet vyziev, aj vypisanie zapasu v user show

**Comment by Felda01** [comment]
pripavene zatial bez upravy poctu vyziev

**Comment by Felda01** [comment]
matches a challenges su softdelete

**Comment by rychtovy24** [comment]
done
